FROM node:18-alpine

WORKDIR /app
# Zainstaluj deps raz (szybsze przebudowy)
COPY frontend/package*.json ./
RUN npm install

# Kod będzie podmontowany z hosta
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

EXPOSE 3000
CMD ["npm", "start"]
