version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: zalpha-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend:delegated
      - ./backend/portfolio.db:/app/backend/portfolio.db
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: zalpha-frontend
    ports:
      - "3000:3000"
    # Podmontuj cały projekt frontu, ale node_modules zostaw w kontenerze
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
